### ISSUE TITLE
helloooo

### ISSUE THREAD

**Issue by ArchKubi** [kame404/Blender-Themes#1]
please can you make like a cyberpunk style theme ?
this is my qtile wm
![2022-01-30-051651_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/151684159-0fff40e9-3e7e-4775-9536-98d163029a19.png)

**Comment by kame404** [comment]
Thank you for your nice request!
I made a purplish theme with red accent colors.
Give me feedback if you have any😎
![cyber_lt](https://user-images.githubusercontent.com/54836559/152026963-bfb99e21-3749-44a5-b4e1-5f0a974aa3b7.png)
[Cyber.zip](https://github.com/kame404/Blender-Themes/files/7980963/Cyber.zip)

**Comment by ArchKubi** [comment]
sooo cool thank you!
![2022-02-02-062655_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/152088600-080394f1-1e48-40b3-9a34-3044131d74ad.png)

**Comment by ArchKubi** [comment]
this is to much to ask but 
you so cool can you make dark purple theme
pretty please

**Comment by kame404** [comment]
Okay. There are many kinds of purple, such as blue-purple and red-purple.
I would like you to create your ideal theme and send me a screenshot, just the property panel part.
Then I will create a theme with that color.

**Comment by ArchKubi** [comment]
![2022-02-03-090248_1280x1012_scrot](https://user-images.githubusercontent.com/80429360/152289749-058349de-f204-44de-844d-d89b859c2846.png)
thanks bro

**Comment by kame404** [comment]
The color was changed to darker so as not to hurt everyone's eyes.
![Amethyst](https://user-images.githubusercontent.com/54836559/152629662-f05dc29a-b2de-4f13-8ef7-4d763b46ea57.png)
[Amethyst.zip](https://github.com/kame404/Blender-Themes/files/8007431/Amethyst.zip)

**Comment by ArchKubi** [comment]
thanks bro 
you the best
