### ISSUE TITLE
could one use these also as official themes for Flax engine

### ISSUE THREAD

**Issue by charlesmlamb** [kame404/blender-themes#11]
these are cool, or could one borrow them

![Screenshot (141)](https://github.com/user-attachments/assets/b5aa620d-951c-43d7-a8d1-489a81892267)

very cool

![Screenshot (142)](https://github.com/user-attachments/assets/489299a8-27e8-4c9f-9822-be2544cd2aa8)

not sure these are copyright., or could try and add them to a video game engine

**Comment by charlesmlamb** [comment]
have tried adding these

![Screenshot (143)](https://github.com/user-attachments/assets/9ff13b13-5155-47ca-ab08-5016bb7bd0ee)

and this

![Screenshot (145)](https://github.com/user-attachments/assets/fe35b19b-bcf3-4544-8bfe-5a0279738464)

**Comment by kame404** [comment]
Hi charlesmlamb,

Thank you for reaching out! I'm glad you like my Blender themes. Especially, the "Choco Mint" theme looks very well reproduced in your screenshot!

You're welcome to use the color palettes from my themes for Flax Engine without any further permission needed. 

Best regards,
