### ISSUE TITLE
Blender 4.3 Editor outline incompatibility

### ISSUE THREAD

**Issue by clausbertels** [kame404/blender-themes#12]
Theme settings changed in 4.3

The Editor Outline is now under User Interface > Styles > Editor Border and is set to black as default.

I recommend setting it to 1.0/white, setting the Editor outline to 0.8/gray and the Active Editor Outline to 0.5/dark-gray

![image](https://github.com/user-attachments/assets/1849e9b7-6b97-41a7-b380-8baae525a2d5)

**Comment by kame404** [comment]
Thank you for the detailed issue report and the theme setting suggestions! I've implemented your recommendations. Please let me know if you have any further feedback😊
