### ISSUE TITLE
Node frames are too dark in the Piano White Theme

### ISSUE THREAD

**Issue by benthillerkus** [kame404/Blender-Themes#2]
![image](https://user-images.githubusercontent.com/29630575/179762273-9417ecb5-cbe2-4abe-9e1c-0626cead67b0.png)

I would suggest setting the `Frame Node` parameter to `.1`:

![image](https://user-images.githubusercontent.com/29630575/179762313-04da573e-2fb4-45b3-9890-fa7895aad268.png)

**Comment by kame404** [comment]
Thanks for the feedback!
I have changed the colors of the `frame_node` to `Piano White` and the `Pastel Pink` theme👍
https://github.com/kame404/Blender-Themes/commit/8cfe36c94813bb6d9155090c693a218e6d2b8e7e
