### ISSUE TITLE
Is the orange theme available?

### ISSUE THREAD

**Issue by leperleep** [kame404/Blender-Themes#3]
In the original screenshot I see an orange theme but It isn't in the download

**Comment by kame404** [comment]
The `Peach` theme is no longer supported; files were removed on December 30, 2021.
16606a3ccd7999eee90cdb399f0990a2a4bba66b
The file can be viewed ![here](https://github.com/kame404/Blender-Themes/blob/9321eea200cc1cfa3e6779427825ea228edc92eb/Peach.xml).

**Comment by leperleep** [comment]
Alright, thank you
