### ISSUE TITLE
how to change bone color?

### ISSUE THREAD

**Issue by jinfagang** [kame404/Blender-Themes#4]

**Comment by kame404** [comment]
`Bone Groups` allow you to change the color of the bones.

`Bone Groups` works only in `Pose Mode`.

For more information, please refer to the [Blender Manual](https://docs.blender.org/manual/en/latest/animation/armatures/properties/bone_groups.html).
![bone_groups](https://user-images.githubusercontent.com/54836559/190407470-e05d74b8-e565-4190-a914-53fa61344983.png)
