### ISSUE TITLE
Getting Piano White as the default included Blender Light theme

### ISSUE THREAD

**Issue by clausbertels** [kame404/Blender-Themes#5]
I'd love to get a more finished version of Piano White into Blender. I'll propose it on devtalk after this issue is closed.
The current Blender Light theme looks more like a zebra theme to me, it's not an actual light theme. I love Piano White, but there's still some usability problems with it. I'll try to - over time - gather them here.

### Issue 1: 
Unchecked Collection checkbox contrast is way too low. In the images I changed it to black. AFAIK It hasn't resulted in other places becoming invisible.
![image](https://user-images.githubusercontent.com/25482509/196634139-ff96aa00-8edf-450c-a3b8-c81156260853.png)
![image](https://user-images.githubusercontent.com/25482509/196633667-f666aa41-339c-46ea-9d92-903137943dfd.png)

**Comment by clausbertels** [comment]
Question: have you done some user tests with video editors, compositors, 2D illustrators, etc. to see what areas of the theme still have problems?

**Comment by kame404** [comment]
Thanks for the great suggestions. I am also interested in including `Piano White` as a preset in Blender.

I agree with you that the color of `Regular` `Selected` should be changed to black.
I found a problem with the `DopeSheet` and `Graph Editor` channels not being color coded, so I fixed that as well. https://github.com/kame404/Blender-Themes/commit/4a0a9860eb71983b84baa2be24119635f6366ce7

### Before
![Piano-White-Previous](https://user-images.githubusercontent.com/54836559/196676655-d6db48fc-cced-4dd3-b378-038f7a6f1c5a.png)

### After
![Piano-White-New](https://user-images.githubusercontent.com/54836559/196676637-6e2e6790-eda0-4378-9577-7c91c78f3934.png)

### Blender Dark
![Bender-Dark](https://user-images.githubusercontent.com/54836559/196676626-2947143a-13fc-48c2-9907-9a20d78cc8dc.png)

**Comment by kame404** [comment]
If it is ok with you, I will close this issue. If you find any problems with `Piano White` or other themes, please open a new issue👍

**Comment by clausbertels** [comment]
> If it is ok with you, I will close this issue. If you find any problems with `Piano White` or other themes, please open a new issue👍

No problem! In hindsight is probably better for documenting purposes anyway.
