### ISSUE TITLE
Theme + custom accentuation

### ISSUE THREAD

**Issue by daxime** [kame404/Blender-Themes#7]
Hi,
How can i add an accentuation to a theme? For example i use  Professional, but a like the red accentuation. I manually modify the pro xml, but when i do this kind of modification 2 or 3 times, it's annoying.

Is there a way to make the change automatically ?

**Comment by kame404** [comment]
This is an unadorned version, but I have created what you requested. I would greatly appreciate any feedback you may have.

https://kame404.github.io/BlenderAccentColorChanger/

**Comment by daxime** [comment]
Thx, i will look a this :)
