### ISSUE TITLE
Choco Mint has unreadable text in Add-ons preferences in Blender 4.2 LTS

### ISSUE THREAD

**Issue by SharkyNebula** [kame404/blender-themes#9]
![2024-09-13 08_55_16-Blender Preferences](https://github.com/user-attachments/assets/6a474694-7ad4-4160-991e-1bebd20f44b3)
Blender 4.2 LTS
Expected result: dark text
Actual result: light text
Fix unknown

**Comment by kame404** [comment]
Thank you for reporting this issue! I've adjusted the Box Text Color to improve readability in the Add-ons preferences!
